# -*- coding: utf-8 -*-
"""PandasStudy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HqZ2HbE5-CSRln816Zf0tiUKZVg7QuAi
"""

import pandas as pd

dados =  pd.read_excel("BRA2022betstats.xlsx")
dados

ResHPal = list(dados["Home"] == "Palmeiras")
dados.loc[ResHPal]

ResAPal = list(dados["Away"] == "Palmeiras")
dados.loc[ResAPal]